apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: dgluhotorenko/authservice:latest
          env:
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: auth-jwt-secret
                  key: Jwt__Key
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: auth-jwt-secret
                  key: Jwt__Issuer
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: auth-jwt-secret
                  key: Jwt__Audience
---
apiVersion: v1
kind: Service
metadata:
  name: auth-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: authservice
  ports:
  - name: authservice
    protocol: TCP
    port: 80
    targetPort: 7000